### ISSUE TITLE
Rover as a Galaxy Server plugin?

### ISSUE THREAD

**Issue by zachcp** [chmille4/Rover#2]
Hi Chase,

Great work on Scribl/Rover.  Do you think it might be possible to use Rover/Scribl with the Galaxy server? For example - put Rover at the end of a gene-annotation workflow so you could analyze your results in the browser?

best,
zach cp

**Comment by chmille4** [comment]
Hi Zach

I'm not sure. Galaxy does have a visualization module called GTB. I'd check that out first.

Though, it is interesting idea. I think it would be really useful for Galaxy to allow visualization "plugins" for cases that GTB doesn't or shouldn't cover.

If you look into the technical side, let me know what you find out.
